@BASE_URL = http://localhost:7071

### Will log EmployeeId in subsequent services
### due to LogContext.PushProperty
GET {{BASE_URL}}/employee/1234/name
 
### Will log EmployeeId in subsequent services
### due to LogContext.PushProperty
### Correlation ID only works in Rider (I think?)
GET {{BASE_URL}}/employee/1234/name

### Will log EmployeeId in subsequent services
### due to LogContext.PushProperty
### (no correlation id)
GET {{BASE_URL}}/employee/1234/name

### Log error
### Request will log a 404
GET {{BASE_URL}}/employee/123/age

### Will log a warning
GET {{BASE_URL}}/employee/12345678912345678912345/age
